// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://knbtzhwyublqroebequr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYnR6aHd5dWJscXJvZWJlcXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjA3MTMsImV4cCI6MjA1OTQ5NjcxM30.-n7nHm5IUFVkeAcGUAsFoDiTUhZKp0MR0cn5y9i-eyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);